client_id='x7hedevilx'
client_secret='	YqQmGoT34zKBs_wMpnST9r-CraqSRA'
user_agent='Saved posts scraper by /x7hedevilx '
username='watershed600rr'
password='MilesNora100'
savedir='C:\Users\water\OneDrive\Documents\GitHub\MINGW-packages\export-archive-reddit-saved'
